version: '2'
services:
  demojhipster-app:
    image: demojhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://demojhipster-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=demoJhipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://demojhipster-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://demojhipster-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8080:8080
  demojhipster-mongodb:
    extends:
      file: mongodb.yml
      service: demojhipster-mongodb
  demojhipster-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: demojhipster-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
